#!/bin/bash

set -u
set -e

PASSWORD="None"

if [ $# -ne 0 ];
then
    PASSWORD="$1"
fi

unzip -P "$PASSWORD" source.zip

mv -v ./source/* .

mv mjkey.txt ~/.mujoco/

rm -rf source.zip source key

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.mujoco/mujoco200/bin

pip install mujoco_py